import { Providers } from "~/src/providers";
import type { Metadata } from "next";
import "./globals.css";
import { Pretendard } from "~/src/shared/fonts/pretendard/Pretendard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Pretendard.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
